# syntax=docker/dockerfile:1
FROM node:20-alpine
RUN apk add --no-cache openssl
RUN corepack enable
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @escola/api exec prisma generate
